### ISSUE TITLE
About the game

### ISSUE THREAD

**Issue by Cosetto** [JuicyStandoffishMan/WhiteAlbumRestorationPatch#1]
Hey there, I wonder if you can share the tools to work for this game? The old tool you once uploaded doesn't work because of the path problem, I tried to modify it but no dice at all.
![image](https://github.com/JuicyStandoffishMan/WhiteAlbumRestorationPatch/assets/81801486/a0002d8b-df0a-43f1-8694-5bd208eb5454)

**Comment by JuicyStandoffishMan** [comment]
Yes, I plan to but just need to clean some stuff up first. It'll be sometime today.

**Comment by Cosetto** [comment]
Looking forward to seeing it!

**Comment by JuicyStandoffishMan** [comment]
It's available in the [master branch now](https://github.com/JuicyStandoffishMan/WhiteAlbumRestorationPatch/tree/master). The steps are more involved now but I think I got everything listed properly. Lemme know if you run into any problems.

**Comment by Cosetto** [comment]
It works great, although I don't have the Japanese version for the jap script. There's another problem, can you make a python to merge all the Excel sheets into a workbook? It because I don't know how to search for the first script. And finally, I recommend moving the Save button to the top because I can't scroll down to it, I recommend this position (450, 40)
![image](https://github.com/JuicyStandoffishMan/WhiteAlbumRestorationPatch/assets/81801486/b45e431a-39ee-4d3a-9cb6-80a46585ee0e)

**Comment by Cosetto** [comment]
Also, do you know how to add more characters to Font.pck? I need to add my language's special characters

**Comment by JuicyStandoffishMan** [comment]
Sometimes I forget I use a 4K display so I hadn't realized the window was gigantic. But yeah, I don't know why I didn't improve the spreadsheet dumping to use 1 workbook. Even in my Aikano translation project I did.

Regarding the font, the original TL project added an English font and it was a gigantic PITA. I haven't looked into it for the remake but it looks like it's probably the same baked bitmap fonts, though now there is support for variable-width characters. You can view an [old version of the repo](https://github.com/JuicyStandoffishMan/WhiteAlbumRestorationPatch/tree/db0e198efb7da7276db002e51c377ac03360ad38) where the readme explained how the font was expanded, but I don't know how much of it nor the code in Form1.cs is applicable anymore. You'll probably have to get your hands dirty with a hex editor and custom code.

Alternatively, maybe the DAL tools used in this repo support font modifications and use the same format as this version of the game.

**Comment by Cosetto** [comment]
So I extracted with PCKtool and got 3 fnt files. Even FontEditor of DALtool doesn't work, but this looks so familiar
![image](https://github.com/JuicyStandoffishMan/WhiteAlbumRestorationPatch/assets/81801486/ee9ed61b-39c2-464c-bbe4-22c4f1c8f021)

**Comment by JuicyStandoffishMan** [comment]
The original game used MAINTEXT.fnt for the in-game display font, and SELECTTEXT.fnt for the menu elements. In Form1.cs, `read_png` showed how it read and replaced the font file (it was two functions in one and I'd comment out certain code, so it's not very clean). But the header format was this:
- "Table" signature. It used to be 8 bytes, but now uses the longer signature and runs through [0, 0x13]
- TEX offset in bytes. It used to be a 4-byte big-endian int but now looks to be little endian, like the other files
- 4 bytes for the character height. Again looks to be little-endian now
- 4 bytes for the character count. There, 0x8D2 closely matches the original 0x880

Then, for every character, it would be 12 bytes:
- 4 byte ID for the character code. It previously used Shift-JIS but now the game uses UTF-8
- Normalized X coordinate offset (32-bit float)
- Normalized Y coordinate offset (32-bit float)

Finally, after each character, it would be the font texture using the TEX format at the offset specified in the header - A "Texture" header, which closely matched the DAL format, and you can actually search for "Texture" in the dumped file. My current code for reading textures doesn't work, so something must've changed, but it's likely a small change. They weren't compressed iirc - just a header containing size and format info, but after that it was just raw 32-bit RGBA values.

I remember why the font modifications were such a PITA - because of the normalized texture coordinates. I had to expand the file and then recalculate the new ones lol. Which sounds simple in hindsight but there was a lot of digging through Ghidra and x64dbg at the time.

**Comment by Cosetto** [comment]
Oh wait, I think this is the tool for it https://github.com/marcussacana/AquaPlusEditor/blob/master/AquaPlusEditor/FNT.cs
![image](https://github.com/JuicyStandoffishMan/WhiteAlbumRestorationPatch/assets/81801486/a1da48e4-c328-4f01-8da0-469b842d8bc0)
Hmm

**Comment by JuicyStandoffishMan** [comment]
That looks like the right format, but that Font Structure.bt needs a couple changes to match the format I described above (which is based on the screenshot you sent). The first character starts at 0x20 and is actually 0x20, which is ' ' (space) and more or less matches that code. It should look something like:
```
typedef struct {
    char UTF8[4];
    float X;//Multiply by the Font Width to get the real value
    float Y;//Multiply by the Font Height to get the real value
} Entry <read=CharRead>;

typedef struct {
    char TableHeader[20];

    int32 TableSize;

    int32 FontSize;

    int32 EntryCount;

    Entry Entries[EntryCount];

    int Padding;

    char TextureHeader[20];

    int32 TextureSectionSize;

    int32 UnkA;
    int32 UnkB;

    int32 TexSize;

    uint16 Width;
    uint16 Height;

    ubyte TexData[TexSize];
} Header;
```

The only differences are the header sizes go from 12 bytes -> 20 and what I called the texture offset is the `TableSize`. I dunno if that `int Padding` is correct, nor the info header after `char TextureHeader[20]`, but the old format at least used int32s for the width/height. That much should be easy to figure out by looking at a hex editor.

**Comment by Cosetto** [comment]
![image](https://github.com/JuicyStandoffishMan/WhiteAlbumRestorationPatch/assets/81801486/55d07258-0e2a-45ab-a199-006f6646acc8)
(Smile gradually faded. JPG)

**Comment by JuicyStandoffishMan** [comment]
Not much to go off of from that screenshot. I guess make sure the data is little-endian and the texture header format is right. I'm not familiar with that code.

**Comment by Cosetto** [comment]
@JuicyStandoffishMan I know this is late to ask, but do you know how to patch the game to make it always render the text as half-width?
In [this repos](https://github.com/marcussacana/AquaPlusEditor?tab=readme-ov-file#executable-patches), Marcus wrote the addresses patch the game with same engine (Mask of Deception). This is how the game looks like:
![image](https://github.com/JuicyStandoffishMan/WhiteAlbumRestorationPatch/assets/81801486/3373945b-6f56-4dde-82ea-4c38966cb531)
But when I tried with White Album (using 0x7706 pattern), it doesn't seem to work for me.
![image](https://github.com/JuicyStandoffishMan/WhiteAlbumRestorationPatch/assets/81801486/8f20bdbe-3c42-4ffc-bea4-110e9a337227)
I'll attach sample file if you need
[WA.zip](https://github.com/JuicyStandoffishMan/WhiteAlbumRestorationPatch/files/15094619/WA.zip)
Ps: Fixed
![image](https://github.com/user-attachments/assets/fe2d8f22-ec6d-4332-99c8-0c4b139a5331)

**Comment by Cosetto** [comment]
[Link](https://github.com/thesupersonic16/DALTools/actions/runs/8814825772/artifacts/1442755654)
